# Config file for automatic testing at travis-ci.org

language: python

sudo: required

dist: xenial

python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

before_install:
  - sudo apt-get -y -qq update
  - sudo apt-get install -y ffmpeg
  - sudo apt-get install -y poppler-utils

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U setuptools && pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox
